author: ${author}
name: ${project.artifactId}
version: '${project.version}'
main: ${main-paper}
api-version: '1.20'
commands:
  cow:
    description: "Spawn an exploding cow."
    usage: "/cow [baby/set] <entity>"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to run this command."
  butterfly:
    description: "Toggle particle effect."
    usage: "/butterfly"
    aliases: [ butterflywings ]
    permission: cowcannon.command.butterfly
    permission-message: "You do not have permission to run this command."
  displayentity:
    description: "Spawns a display entity."
    usage: "/displayentity [item/block/text]"
    aliases: [ de ]
    permission: cowcannon.command.displayentity
    permission-message: "You do not have permission to run this command."
