author: ${author}
name: ${project.artifactId}
version: '${project.version}'
main: ${main.paper}
api-version: '1.20'
softdepend: [ ProtocolLib ]
commands:
  cow:
    description: "Spawn an exploding cow."
    usage: "/cow [baby/set] <entity>"
    aliases: [ cowcannon ]
    permission: cowcannon.command.cow
    permission-message: "You do not have permission to run this command."
  butterfly:
    description: "Toggle particle effect."
    usage: "/butterfly"
    aliases: [ butterflywings ]
    permission: cowcannon.command.butterfly
    permission-message: "You do not have permission to run this command."
  displayentity:
    description: "Spawns a display entity."
    usage: "/displayentity [item/block/text]"
    aliases: [ de ]
    permission: cowcannon.command.displayentity
    permission-message: "You do not have permission to run this command."
  customitem:
    description: "Gives you a custom item."
    usage: "/customitem"
    aliases: [ itemcustom ]
    permission: cowcannon.command.customitem
    permission-message: "You do not have permission to run this command."
  gui:
    description: "Opens a GUI."
    usage: "/gui"
    aliases: [ ]
    permission: cowcannon.command.gui
    permission-message: "You do not have permission to run this command."
