# !-----------------------------------------------------------------------------------------------!
#                       Bem-vindo à configuração principal do ${project.name}
# !-----------------------------------------------------------------------------------------------!
#
#    Esta é a classe de configurações principal do plugin. Você pode usar o SimpleSettings para carregar valores dela,
#    e atualizá-la automaticamente.
#
#    Para suporte e documentação, por favor visite:
#    - https://github.com/${author}/${project.name}/wiki
#
# !-----------------------------------------------------------------------------------------------!
#
#    1) CÓDIGOS DE COR são suportados com o caractere '&'.
#       - Para uso, veja http://minecraftwiki.net/wiki/Formatting_codes
#       - Quando você os usar, coloque aspas ao redor da mensagem assim: "Hello &cworld."
#       - Para usar cores HEX, use a sintaxe #123456: "Hello #123456world."
#
#    2) PARA OCULTAR qualquer mensagem, defina como 'none'.
#
#    3) Para CARACTERES UNICODE (emojis, símbolos, ..), salve o arquivo em codificação UTF-8. Veja
#       - https://github.com/${author}/${project.name}/wiki/Use-Right-Encoding
#
#    4) JSON é suportado.
#       - Para uso, veja https://github.com/${author}/${project.name}/wiki/JSON
#
#    5) LISTAS DE PERMISSÃO podem ser transformadas em listas de bloqueio, colocando "@blacklist" na primeira linha.
#       - Ao fazer isso, os filtros serão aplicados apenas para mensagens nessas listas.
#
#    PS: Tudo acima se aplica a todos os arquivos na pasta ${project.name}/.
#
# !-----------------------------------------------------------------------------------------------!

# -------------------------------------------------------------------------------------------------
# Os formatos usados em {date}, {date_short}, {date_month} e {location}.
#
# Veja o link abaixo para aprender como editar o formato da data:
# https://docs.oracle.com/javase/8/docs/api/java/text/SimpleDateFormat.html
# -------------------------------------------------------------------------------------------------
Date_Format: "dd.MM.yyyy HH:mm:ss"
Date_Format_Short: "dd.MM.yyyy HH:mm"
Date_Format_Month: "dd.MM HH:mm"
Location_Format: "{world} {x}, {y}, {z}"

# -------------------------------------------------------------------------------------------------
# Quais comandos devem acionar o grupo de comandos principal do plugin?
#
# * O PRIMEIRO APELIDO É O LABEL PRINCIPAL, VOCÊ PODE ALTERÁ-LO MAS NÃO O REMOVA. *
# * EXEMPLO: [boss, b] acionará seu comando principal a partir de "/boss" ou "/b" *
# -------------------------------------------------------------------------------------------------
Command_Aliases: [cowcannon, cc]

# -------------------------------------------------------------------------------------------------
# Qual idioma devemos usar para as mensagens? Se existir, o arquivo de idioma será copiado
# para sua pasta messages/, onde você poderá editá-lo.
# -------------------------------------------------------------------------------------------------
Locale: pt

# -------------------------------------------------------------------------------------------------
# O prefixo usado na frente da maioria das mensagens no chat ou console. Você pode usá-lo manualmente com
# a variável {plugin_prefix} em qualquer lugar.
# -------------------------------------------------------------------------------------------------
Prefix: "&8[&c${project.name}&8]&7"

# -------------------------------------------------------------------------------------------------
# O tempo de algumas operações do plugin é medido. Você também pode usar a classe LagCatcher para invocar
# este recurso. Registramos uma mensagem no console se uma operação demorar mais do que o tempo abaixo (milissegundos).
# Defina como -1 para desativar.
# -------------------------------------------------------------------------------------------------
Log_Lag_Over_Milis: 100

# -------------------------------------------------------------------------------------------------
# Lista de nomes de seções que exibirão mensagens informativas sobre os recursos deste plugin.
# A classe Debugger utiliza esta chave e só exibirá mensagens para as seções ativadas abaixo.
# -------------------------------------------------------------------------------------------------
Debug: []

# -------------------------------------------------------------------------------------------------
# Não altere este valor, caso contrário, isso corromperá a instalação do seu plugin!
# NB: Não se esqueça de manter isso atualizado com o método getConfigVersion em sua classe Settings.
# -------------------------------------------------------------------------------------------------
Version: 1
